---
title: Hans Kristoffer
timezone: UTC
collections:
  blog-kategorier:
    title: Blog Kategorier
    output: true
    permalink: "/blog/:title/"
  blog-posts:
    title: Blog Posts
    output: true
    permalink: "/blog/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: "/pages"
    type: pages
  values:
    title: 
    meta_beskrivelse: 
    cover_image: 
    permalink: 
    layout: default
    is_post_layout_page: false
- scope:
    path: ''
    type: blog-posts
  values:
    title: 
    meta_beskrivelse: 
    blog-kategorier: 
    post_date: 
    cover_image: 
    post_image: 
    layout: blog-post
- scope:
    path: ''
    type: blog-kategorier
  values:
    title: 
    meta_beskrivelse: 
    layout: blog-kategori
    cover_image: 
- scope:
    path: ''
    type: boeger
  values:
    title: 
    forfatter: 
    stjerner: 
    link: 
    kategori: 
    bedste-laering: 
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: https://hanskris.dk
typekit_id: lqi5hgi
html_lang: en
google_analytic: UA-100587614-1
facebook_id: 
markdown: kramdown
gems: 
exclude:
- Gemfile
- Gemfile.lock
- "*.jade"
