# Site
title: Hans Kristoffer
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hanskris.dk" # the base hostname & protocol for your site, e.g. http://example.com

# Other
typekit_id: lqi5hgi
html_lang: en

# Analytic
google_analytic: UA-100587614-1
facebook_id: #

# Collections
collections:
  blog-posts:
    output: true
    permalink: /blog/:title/

  blog-kategorier:
    output: true
    permalink: /blog/:title/


# Defaults
defaults:
  -
    scope:
      path: "/pages"
      type: pages
    values:
      title:
      meta_beskrivelse:
      cover_image:
      permalink:
      layout: default
      is_post_layout_page: false

  -
    scope:
      path: ""
      type: blog-posts
    values:
      title:
      meta-beskrivelse:
      blog-kategorier:
      post_date:
      cover_image:
      post_image:
      layout: blog-post

  -
    scope:
      path: ""
      type: blog-kategorier
    values:
      title:
      meta-beskrivelse:
      layout: blog-kategori
      cover_image:

  -
    scope:
      path: ""
      type: boeger
    values:
      title:
      forfatter:
      stjerner:
      link:
      kategori:
      bedste-laering:

# Build settings
markdown: kramdown

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.jade"
