# Site
title: Hans Kristoffer
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hanskris.dk" # the base hostname & protocol for your site, e.g. http://example.com

# Other
typekit_id: lqi5hgi
html_lang: en

# Analytic
google_analytic: #
facebook_id: #

# Collections
collections:
  blog:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: blog
    values:
      layout: blog-post
      permalink: /:collection/:path/

# Build settings
markdown: kramdown
permalink: pretty

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.jade"
